### ISSUE TITLE
Potential improvements for The world of Machine Learning with Knet course on JuliaAcademy.com

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#25]
Thread created during Google Code-In.

**Comment by KhushalNirwal** [comment]
This tutorial was good for the people who wanted to learn Machine Learning(especially with Julia). I liked this course and I think this course was very knowledgeable.

**Comment by KhushalNirwal** [comment]
For the improvement in this course, instead of running these videos linked to youtube you can use HTML 5 or Flash Player and I think you should also increase the size of the player window. And speaking of the course there were some instants where the teacher/master/host was not that much excited but otherwise, the course was wonderful, it looked that Deniz Yuret was an expert and I think he should add some more courses because in the future machine learning is going to be a big part of the technology and lastly, I would like to say thank you to GCI community of Julia to introduce me to such a nice course and thanks to logankilpatrick for helping me to improve my comment.

**Comment by mikolajhojda** [comment]
I don't like a link to Youtube to see a video. I want to see a video like in "Introduction to Julia". The topic of the course is very interesting because I didn't know what is Knet before doing it. Maybe a transcription of the course is a nice idea. I have a problem with learning from a video.

**Comment by TheComputerM** [comment]
The course is extremely informative and great but some additions would make it even better:

- Learners cannot keep track of their performance so the addition of reviews would make it interactive as well as would help the users to keep track of their performance.

- The sound quality is good but the addition of subtitles would make it easy for learners to follow along much efficiently.

- The videos are embedded from YouTube and have a small size and it would be better if they were integrated into the website like the videos of the "Introduction to Julia" course.

- The course should be divided into beginner and advanced parts to make it easier for users to learn much more efficiently.

**Comment by sbhavyasivaraj** [comment]
Machine learning with knet seemed very hard and tough to understand. Initially, I thought I would not understand it clearly. But the instructor had managed to make it a bit understandable. The concepts which were introduced in the videos are all known to me by name. (i.e) Natural Language Processing, Deep Learning, Neural Networks, etc. which are all part of Artificial Intelligence. We have just started learning about this in our school. But, from students’ point of view, it is going beyond my head. The concepts could have been demonstrated in a simplified manner.
One important suggestion I would like to give is that compared to the other courses or lectures of Julia, this is very vague, I would say the other ones were far better in terms of clarity. There is no interactive session due to which the course is very boring. The kids wouldn’t find this course as a fun filled one because each and every year a new set of beginners are starting to do GCI and when the courses go boring they would not like to do them with interest. The instructor can give more examples to the explanation and they can be more interesting because the importance of the series of videos in this lecture is very high. When some task is done related with Machine Learning with knet, it would be utilized. Hence the video can be improved with lot of expressive communication which was lagging and the level of the lecture could also be such that it caters to high school students level.

**Comment by sbhavyasivaraj** [comment]
Machine learning with knet seemed very hard and tough to understand. Initially, I thought I would not understand it clearly. But the instructor had managed to make it a bit understandable. The concepts which were introduced in the videos are all known to me by name. (i.e) Natural Language Processing, Deep Learning, Neural Networks, etc. which are all part of Artificial Intelligence. We have just started learning about this in our school. But, from students’ point of view, it is going beyond my head. The concepts could have been demonstrated in a simplified manner.
One important suggestion I would like to give is that compared to the other courses or lectures of Julia, this is very vague, I would say the other ones were far better in terms of clarity. There is no interactive session due to which the course is very boring. The kids wouldn’t find this course as a fun filled one because each and every year a new set of beginners are starting to do GCI and when the courses go boring they would not like to do them with interest. The instructor can give more examples to the explanation and they can be more interesting because the importance of the series of videos in this lecture is very high. When some task is done related with Machine Learning with knet, it would be utilized. Hence the video can be improved with lot of expressive communication which was lagging and the level of the lecture could also be such that it caters to high school students level.
sbhavyasivaraj- Github username

**Comment by ABHI-310** [comment]
I liked the course very much, everything seamed to be very simple. It was great learning MACHINE LEARNING, and that too in Julia language. The mentor made me understand everything very easily .I would like to suggest some enhancement in the course by the addition of practice exercises for evaluation.

**Comment by CompSciDZ** [comment]
(FYI) Typo on task description on GCI - it says to take the Intro the Julia course and finish it 100% while it should be The world of Machine Learning with Knet.

The course is well designed with videos to help explore machine learning. The instructor does a good job of explaining each concept and uses various resources to help convey the point. I would like the addition of additional resources to check out (links, try it yourself, etc.) and interaction between the user and JuliaAcademy through the use of quizzes, etc.  I like how the instructor solves a data problem together in a Julia sense can also be incorporated (ex. Write code that does this…) to help with future tasks and problem-solving with machine learning. Practice is a great way to learn!

Overall, I enjoyed the course and think it is great for teaching and learning Machine Learning!

**Comment by josobar** [comment]
For me, this course helped me understand the topic very well. The instructor is obviously a very qualified expert and presents examples that help the viewer apply these ideas to real-world situations. Overall, it is a great course but is not without some potential improvements. 

Suggestions:
- The instructor's speech is sometimes hard to understand, but most of the time it is clear. A transcript of the course or subtitles could prevent this.
- A common trend among these courses is a lack of interactivity. Perhaps a few quizzes or maybe a whole new form of user interactivity could be implemented in order to keep the viewer engaged.
- The instructor spends a lot of time in Jupyter notebook, and some of the longer sections could use a change of scenery such as a graph or other kind of visual aid.

**Comment by ishita272001** [comment]
It was a good course.I learned a new topic and got to learn about machines with knet. It will be more better  if some improvements are made.
1.As the link is uploaded from YouTube.It would be better if the video is like what is in  "Introduction to Julia".
2.Some tests at last should be added.
3.I faced an error.
![error](https://user-images.githubusercontent.com/59233460/71712915-6ae4b180-2e2d-11ea-9f74-b4a127ca36cd.PNG)
![error 2](https://user-images.githubusercontent.com/59233460/71712917-6c15de80-2e2d-11ea-98d6-3aabf80f7d45.PNG)
4.When I opened the PDF it contains code and the codes were not in an organized way.
Otherwise the course was good
HOPE YOU MAKE IMPROVEMENTS ON THE ISSUES I TOLD.
THANKS

**Comment by chinglamchoi** [comment]
1. VQA is no easy beginner task, it is a cross-modal task and requires knowledge of attention mechanisms as well
- Might not be the most ideal first lecture (after intro) for a course

2. Although I really appreciate that he provided the paper for us as reference, some basic overview or summary on the paper would have been nice before jumping straight in and running the code. Elaboration on the contributions, results and distinctions of the paper & its method would really have enriched the lecture. 

3. Really appreciated how he plotted the image attention map and tested the program using custom questions, but how does it all work?? How did they encode the image features? What attention mechanism did they use? How did they encode the sentences? Word2vec? Transformer? How did they map text and image features into joint (cross-modal) feature space? How did they quantify the similarity between image vectors and word vectors?
- This also true with MNIST, Sentiment Analysis, VGG, where there wasn't a lot of explanation on the methods used.
- Language modeling was explained in great detail though!

4  The organisation of lectures was slightly confusing. MNIST and image classification are much more basic tasks than VQA, yet VQA was touched on first. Perhaps re-ordering the lectures could better build up students' knowledge, thus enabling the instructor to elaborate more on the details of various papers.

5. The code in the MNIST notebook was very comprehensive. The code walks us through firstly, setting up the dataset; secondly, defining our model architecture; eventually, hyperparameter tuning and training; which enables us to reliably reproduce results of the notebook. It would have been even better if the instructor explained the theory behind the code (e.g. going over the layers of lenet, briefly talking about the effect of strides and paddings, touching on how and why (semantic deep features) channels are added, while the physical image dimensions are downsized.

6. I really appreciate how he plotted graphs to compare and contrast between the performance of different models (MLP vs CNN), and visualised their loss over epochs.

7. Instead of only demoing pre-trained language and image models, perhaps the instructor could have implemented one basic model with us (e.g. the MNIST model). I can see that Knet works is very convenient, but I have no idea how anything works and how I can customise network functions/architecture.

**Comment by ABHI-310** [comment]
The course was very helpful. I completely enjoyed learning Machine learning with Knet (in Julia Language).The mentor had rich knowledge of the language which does not leaves any doubt behind . I would recommend to make the lectures a little more interactive.

**Comment by Dhanus3133** [comment]
1. To add Dark mode feature in the Settings 

2. To add a quiz after the completion of the concept in the video

And rest of the track were good

**Comment by ABHI-310** [comment]
1. The first time I submitted the task it was rejected due to the typo in GCI task description, the organisation in charge should be more careful while uploading the task details.
2. Well, I learned a lot during the course of Machine Leaning with Knet ( using Julia Language).The course was very helpful.The mentor had rich knowledge of the language which did not leave any doubt behind . 
Recommendations:
[a] Please try to make the lectures more interactive, by just not explaining the pre typed code but also solve a question related to it during the lecture so that students can think and learn on the go.
[b] Add quizzes after every lecture video for practice and evaluation purposes, by this the students will know the areas they lack practice in.

All in all the course was good and helpful as a new coder.

**Comment by kchatr** [comment]
This course was good from a theoretical point-of-view and seeing how the abstraction of a neural network functions. The material was relatively in-depth and contained helpful notebooks that supplemented the lessons. It showcased a Julia package and how that package can be used while going through the abstraction of it.

For a course dubbed _The world of Machine Learning with Knet_, it had very little information on how to gather data and implement it in Julia. The Code Samples are not intuitive and I feel that there were a lot of corners cut when explaining the code and how it works. I understand that Knet has tutorials on their GitHub repo, but it would be helpful to go over the code and state what the variables and functions represent. It does not go into a full explanation of either the concept or the code, which I found quite disappointing. 

For the Handwriting example, the instructor does not go into detail about how the model works or trains, and the entire exercise appears as more of a BlackBox. The actual workings of a convolutional neural network and how it is implemented in code is never explained, and we are simply shown the end result. There were a lot of key terms used not very clearly explained, as well.

The course assumes knowledge of neural networks and the structure and implementation behind RNNs and CNNs. The NNs themselves are imported, which isn't bad, but it would be helpful if a behind-the-scenes look was provided.

Not a bad course, but I didn't come out of it knowing how to use or implement the functions and modules in Knet, and didn't learn a whole lot regarding CNNs and RNNs.

**Comment by PseudoCodeNerd** [comment]
Okay so the course in itself is highly in-depth but I couldn't comprehend how it started with. It all seemed rushed to me. It was from the second video that I began to understand the flow and sequence of the lectures. No doubt the instructor is an expert in this field and he accomplishes a great job at making us understand even the tougher concepts. However I think that the code samples provided weren't quite as informative. I thought that I would be given at least some intuition about CNN/RNN in general but that didn't happen. This course according to me should be labeled as advanced material. Deep Learning with Flux was **very** exciting and informative. Not that this course lagged in quality content but it could definitely be made better. 
Things I wished were made available :
1. A transcript. I had to rewatch some of the course videos and had difficulty in finding where that concept was discussed in the long videos.
2. Better Lecture Videos. I found out that the instructor's screencast was a bit laggy and not that fluid. Also, the videos could be made bigger (and maybe ported over the platform itself :D)
I agree with @chinglamchoi . A better option would have been to start with the MNIST task as it's easy to understand instead of starting with VQA, whose lectures I myself had to view 2 times. 
I also understand that this isn't a college course where we're taught the exact working of many of the algorithms, but a little bit of extras wouldn't harm 

That's it I guess. With the suggestions given by many of us, I believe that It can indeed be a better course.

**Comment by ABHI-310** [comment]
Some practice exercises, demonstrating the applications of the things learned in the lecture would be appreciated. Because right now I do know how to use the attained knowledge but don't know where to. That is what is required, some exercise questions that should be decided by the mentor himself in order to provide better knowledge of the subject. : )

**Comment by shyamvyas890** [comment]
Hello, I hate to tell you, but this course was not the best course. Although I acknowledge the great efforts he put in, all the course did was show a guy using machine learning in his everyday life, but didn't show what goes on behind the scenes and how to code machine learning programs in Julia.

Also, all courses should have quizzes, homework, and tests to assess whether someone has actually understood what is being taught or not. This course just has a few youtube videos, which might as well be compiled into a YouTube playlist.

Furthermore, the man in the videos speaks extremely slowly, and I had to put it on 2* speed just to concentrate on what that guy was saying. The guys was also speaking extremely softly, so I had to greatly crank up my volume to hear even what he was saying.

Also, for the latter videos, the person filmed had 3 walls and a closet right behind him (as opposed to just him) which gave an extremely unprofessional look to the audience. This could make people distrust the course and look for other courses to learn machine learning.

Also, I couldn't click the next video for it to count towards my progress, because if I did that, my progress would remain the same. I had to click "complete and continue" and then only would it count towards my progress. that was extremely weird, since someone could just watch none of the videos and just click next, next, next, and get 100% complete on their course.

**Comment by aftex261** [comment]
Hey ,I would like to say the course is worth being taking and a good one.
But as nothing becomes better without improvement.
So, Places of improvement:-
1.Firstly I would like to say the course page should be redesigned from backend as it's a bit laggy.
2.The visual Qna regarding the shapes ,sizes and position of different surfaces can be explained  more in a better way for beginners.
3.The Handwriting recognition in julia lecture was good but taking in consideration interactiveness ,and quality content was not much good.
More basic applications can be explained.
4.The language modelling lecture was a good one but was fast paced.
5.The image classification lecture in which you took the example of great dane was good but there should be practice set at the end of course to check how a student is going throughout the course curriculum. 
At last,I would like to say if these improvements will be made then it will be a better one.
So,I would like to say that i would like to rate this course :-3.7/5
Thank you.

**Comment by Delta456** [comment]
The tutorial was hard to understand at first time. I was able to understand after going through some other tutorial and I think that should not be the case. I prefer course videos should not link to YouTube videos. I also faced an error; when I completed the course it shows 100% outside but 0% inside. I think the instructor can give more examples to the explanation and they can be more interesting because the importance of the series of videos in this lecture is very high.

Overall, it is fine and it can be improved!

**Comment by Redeem-Grimm-Satoshi** [comment]
This course was a little bit tough for me but did make it to the end. But the course had a few issues which can be improved.

1. The video was laggy. the transition wasn't smooth

2. I think the video should be placed directly on the platform, not from youtube.

3. The Complete and Continue option makes it easy for anyone to complete the course without actually watching the tutorial videos till the end, I think if it's possible they make it in such a way that when watching a video you must complete it till the end before the Complete and Continue button is enabled. 

That's all for the improvement, the instructor did a great job!

**Comment by aasangamnerkar** [comment]
The course was a bit hard to understand at first, and I had to rewatch it a couple of times to understand it. There are certain things that could improve it however
1. Practice Exercise and other datasets to work with would prove beneficial in this course
2. Loading the video on the actual site instead of YouTube would reduce lag
3. Removing Complete and Continue would stop people from skipping through the content in the course
![image](https://user-images.githubusercontent.com/36603983/72023914-b934ee80-3239-11ea-9655-6f2ccaed86d2.png)

**Comment by TARUN49157** [comment]
The course was a bit hard to completely understand it for the first time,i had to rewatch it again to understand the concepts.It was really good that the certificates were generated at the end of the course.
One suggestion is that you can put a quiz or a test at the end of the course so that we can understand how much we really learnt.

**Comment by mehardeep88** [comment]
The course needs some improvements like there should have been a QnA video at last about the problems and doubts faced by the students during the course. It's great to add ipython notebooks for a student to try hands on. Programming exercises and a mini project should also be uploaded on notebook  (considering it as a test) like a graded assignment for self-evaluation.
![Annotation 2020-01-09 235459](https://user-images.githubusercontent.com/42536877/72094226-ee296a00-333b-11ea-83a8-26a8a310d4a3.png)

**Comment by D3nii** [comment]
The biggest improvement that can be done is to link the page with the Jupytor Notebook, create a full tutorial there and then link it just like University of Michigan does in its Python courses on Coursera. That would increase the explanation and learning rate drastically. Next, I would like to see some links here and there after watching the videos for example a blog to read or in depth differences between artificial intelligence and deep learning. Then, I'd also like to see a path way made for what to do after this course for example either to wait Julia Academy to make the next course or to continue studying somewhere else. And the youtube link is so tacky and small window what it almost makes the website seem fake.

**Comment by rcalitlk** [comment]
I think the course was great. There wasn't anything negative about the concept for me, but in terms of User Interface, I believe it would be better to have the video player of other courses such as "Introduction to Julia Programming Language" rather than having a YouTube player. Other than that, I think it would be better to have some parts that we could evaluate ourselves using some tests, questions, etc. Other than that, everything was nice.

**Comment by nika02** [comment]
The first few lines of code that were ran in the "Visual Question and Answering" section could still be briefly explained even though it was skipped over since that code needed to be run first for the rest of the code to work. Thus, without the explanation, it could leave viewers wondering how it would work exactly. The "Visualisation" sub-section was really neat! It was very interesting to see how the model interpreted the question and how it responded in relation to the image.

For the "Handwriting Recognition in Julia" section, I feel that the sub-section of CNN vs MLP was nice because it proves a comparison for the viewer to see how CNN competes. The explanation of the graph was also done really well. Even for the people that do not have or do not have a good understanding of what multi-layer perception and CNN is would still understand the point the graph is trying to prove.

For the "Sentiment Analysis" section, how the sample data was processed was explained clearly and was easy to follow. The whole section had very good flow to it with the sub-sections :)

Using 2 different examples in the "Language Modelling" was a good way to show how the model understood what it was given. The explanation that was paired with this was also clear.

**Comment by NoorHasanShaik86** [comment]
The course is so good . I liked the course very well and The instructor explained well. but
Use daily life challenges as examples in the course.
Provide some quizzes which will give the progress.
These two are the improvements those I found in the course.
Thank You

**Comment by eahmed123** [comment]
I have done the course. This course was amazing and give me good knowledge of Machine Learning buty there were some problems in the course like there was no quiz at all in the course. That was very weired. If there would be some quizzes so the students can be reviewed how much they understand.
There should be at least two to three quizzes in the course to judge the knowledge of the student. I am going to add some sample questions. Like how the quiz should be.

**Comment by eahmed123** [comment]
I have seen there were some questions as a visible quiz, however, that was not enough to test the knowledge of the learner so there should be proper questions and there should be alloted time to compelete the task. I am adding the sample question how it should be like.
The sample question should be like...
Question 1: This course is about processing natural language through Julia?
A. True
B. False

**Comment by rudy221203** [comment]
The course for me was very educational and explained a lot of mechanics that were not explained to me ever before! The only two things that I would point out to improve would be:

1.) User friendly pop ups (ex. Questions, Comprehensions)
What I mean by this is that as the video is finished for the user, the user should be prompted further information based on the video and should be given questions based on the video.

2.) Video Explanation
What I mean by this is that the trainer should explain further and should make a connection to the roots of the lesson and how this information will be helpful in the near future.

**Comment by aartiojha** [comment]
The course provide by Julia Academy in machine learning is good the way of explain the importance of models is good in each video lecture mentor explain the models and explain it's implementation as well. In Handwriting Recognition the mentor explain the CNN (convolutional neural network) which is very helpful for me. In Sentiment Analysis is the part of NLP was a good lecture its easy to grab what mentor want to explain.The Language Modelling lecture was explained clearly and i understood how to it's works.
![Screenshot (100)](https://user-images.githubusercontent.com/58442386/72673963-3876bd80-3a97-11ea-861a-c264f12d2fb3.png)

**Comment by dhruv2604-create** [comment]
Hi everyone! I recently completed "the world of Machine Learning with Knet" course Course on Julia Academy. After completing "the foundations of Machine Learning" course, this one helped me enhance my knowledge even further. Although there are some suggestions that I would like to make:-

1)There should be comment sections where users can complement as well as ask questions based on the lectures and the lecturers can answer. Also, certain live QnAs should be held with users to further develop knowledge of users.
2)New courses should be made aligned with new versions of Julia.
3)There should be a feature for users to practice alongside listening to lectures on the site itself.
4)Tests should be taken after a user completes a certain component of the course and he or she should only be able to advance after successfully completing the test.
