### ISSUE TITLE
Potential improvements for the Parallel Computing course on JuliaAcademy.com

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaComputing/JuliaAcademyMaterials#27]
For Google Code-In.

**Comment by NoorHasanShaik86** [comment]
The course is good . We can understand it easily. But the course should contain some more like quizzes etc., and the course should contain real life examples also.

**Comment by soumitradev** [comment]
This course is great, but it can do with some improvements:
- The video and audio stutter sometimes since the videos are recorded as a conference call, and network issues during recording have caused stuttering.
- Some of the videos may need to be updated since Julia received enormous updates for parallel processing in 1.2 and 1.3 many of which make algorithms shown in the course much easier.
- The progress bar bug seems to have gone! 👍
- The course content could be made more interesting by adding pop quizzes. One such quiz is included in the video "Tasks (Co-routines)", and it really makes the video interesting.
- The video "Distributed Computing" is too long (66 minutes). Maybe this video can be split into a few parts with quizzes in between?
- Audio quality is not that great.

**Comment by chinglamchoi** [comment]
1. Really appreciated the fine-grained explanations about how each little part of the code can impact the performance:
- e.g. data type: float32 vs float64
- using profile to determine which line of the function (e.g. moving data) is taking up time and needs optimisation
- benchmarking handwritten versus built in functions
- comparing and contrasting between different languages (C, Python (Numpy))

2. Really liked how he outlined the purpose, criteria and impact of each action before proceeding. 
- e.g. giving an overview of the reasons, methods and challenges for parallel processing
- outlines the criteria (what he's looking for in benchmarking) before benchmarking
>> This makes it much easier for us to follow and understand the purpose behind everything he does

3. Although it was nice that he took the time to explain very test case (even just general programming concepts), perhaps it would be useful to cut straight to the chase and focus on benchmarking. But then again, I really appreciated how he went over the functions of each library, interpreting the output with us, teaching us which types/lines of output to attend to. Also, it was extremely helpful that he went over the best practices (for example in the SIMD video) and things to watch out for (e.g. not to use if-else, AX-512 support, verifying the number of cores, oversubcription, false sharing), when going over each library.

4. Perhaps the videos can be broken down to separate shorter ones. dividing them makes them easier to conquer and understand!

5. Also, this is rather advanced knowledge, so perhaps more short quizzes (though they already are some integrated into the course lectures) could be added at the end of each section to help better consolidate knowledge

6. I really liked the approach he used to illustrate the virtues of parallelism. He quoted real life data (moore's law plateuing for single core processing) as well as used benchmarking, profiling, vectorisation, multithreading versus versus atomics to empirically illustrate the benefits for parallel computing.

7. The audio quality for the Performance Overview lecture and onwards were slightly echo-y and unclear

8. Really liked how he has short summaries ("Take always from X") as sort of a conclusion to each new concept

9. Really nice that he explained exactly what operation GPU accelerates (mat mul), I'd always wondered! Furthermore, I loved how he explained the parallel processing capabilities of GPU down to the hardware "warp" level! The amount of detail in this course is amazing!

**Comment by NoorHasanShaik86** [comment]
The course is good and we can understand it well,but
1. The audio is not clear 
2. The video should be  make into parts because continuous listening of a long video creates boring, Dividing the videos into shorter makes the concept easier to understand.
3. The video clarity should be some more better 
4. The course should contain some quizzes and the quizzes make the video interesting .
5. In parallel computing the videos are too long which are getting bored, if the video is divided into parts the video will be interesting.

Other than those the courses are very good and nice experience.

**Comment by sbhavyasivaraj** [comment]
Initially Parallel computing course was not very attractive for me. But as I started going through it, I gained interest. It would be good if there were more questions after all the lectures because there should be a test on what the user had understood so far. It is understandable but it would better for kids if there were more interesting subtopics and examples.  It would have been better if the instructor had been clearer. Overall it was a good lecture, just on these aspects, as mentioned above, if it can be changed it would be a great course for kids. I observed the fact that the other videos or courses of Julia academy is not so long, it is just around 5-10 minutes, and this one is so long. I had to make this comment because the beginners who join and wish to do GCI and choose Julia will most probably lose interest if the find the duration of the courses to be so long.
Thank you.
Bhavya S

**Comment by CompSciDZ** [comment]
Really neat and well-taught course! At the beginning, you really don't know exactly what to expect, but the intro videos give you a clear description of what is taught.

There was switching around with the videos and audio quality, however, that wasn't an issue that affected the learning experience.

The course mainly focuses on the application of Julia and the features of it that are interesting that most of us don't know about. This course is a great way to end JuliaAcademy by giving students an application of the Julia programming language and what it is capable of.

I think it would be better to split this course into 2 parts: Single Core and Parallel to avoid the lengthiness.

The addition of concept checks I think would make a great addition to this course, simply because the videos are long and users may tend to get distracted, so quizzes/some form of interaction with the user are a great way to reinforce concepts and assess proficiency on a certain skill.

Thank you Julia developers for making Julia Academy, offering all these courses and making them available to everyone for free! I appreciate everything that is shared through these courses, especially the knowledgable instructors and skills explored!

**Comment by mikolajhojda** [comment]
I think the course focused very interesting topic. I didn't know anything about it before.
I had a problem with focus because of to long videos. It should be a bit shorter. As I said in another feedbacks. The course needs reviews or tests. It is very important for me because I could better remember topic thanks to it.

**Comment by sbhavyasivaraj** [comment]
Initially Parallel computing course was not very attractive for me. But as I started going through it, I gained interest. It would be good if there were more questions after all the lectures because there should be a test on what the user had understood so far. It is understandable but it would better for kids if there were more interesting subtopics and examples. It would have been better if the instructor had been clearer. Overall it was a good lecture, just on these aspects, as mentioned above, if it can be changed it would be a great course for kids. I observed the fact that the other videos or courses of Julia academy is not so long, it is just around 5-10 minutes, and this one is so long. I had to make this comment because the beginners who join and wish to do GCI and choose Julia will most probably lose interest if the find the duration of the courses to be so long.
Thank you.

**Comment by BhagathUma** [comment]
Initially Parallel computing course was not very attractive for me. But as I started going through it, I gained interest. It would be good if there were more questions after all the lectures because there should be a test on what the user had understood so far. It is understandable but it would better for kids if there were more interesting subtopics and examples. It would have been better if the instructor had been clearer that is, his voice modulation and so on, I don’t know if I was the only one who faced audio problem but if its for many people, it can be changed. Overall it was a good lecture, just on these aspects, as mentioned above, if it can be changed it would be a great course for kids. I observed the fact that the other videos or courses of Julia academy is not so long, it is just around 5-10 minutes, and this one is so long. I had to make this comment because the beginners who join and wish to do GCI and choose Julia will most probably lose interest if the find the duration of the courses to be so long.
Dear mentor, herewith I am attaching the screen shot of the finished task (Parallel Computing).

**Comment by BhagathUma** [comment]
Initially Parallel computing course was not very attractive for me. But as I started going through it, I gained interest. It would be good if there were more questions after all the lectures because there should be a test on what the user had understood so far. It is understandable but it would better for kids if there were more interesting subtopics and examples. It would have been better if the instructor had been clearer that is, his voice modulation and so on, I don’t know if I was the only one who faced audio problem but if its for many people, it can be changed. Overall it was a good lecture, just on these aspects, as mentioned above, if it can be changed it would be a great course for kids. I observed the fact that the other videos or courses of Julia academy is not so long, it is just around 5-10 minutes, and this one is so long. I had to make this comment because the beginners who join and wish to do GCI and choose Julia will most probably lose interest if the find the duration of the courses to be so long. Dear mentor, herewith I am attaching the screen shot of the finished task (Parallel Computing).

**Comment by sankalpdass** [comment]
*Feedback*


![PhotoEditor_20200106_205122715](https://user-images.githubusercontent.com/56037184/71829242-33defc00-30ca-11ea-8553-439f6f909f4c.jpg)


Actually when I claim the task to watch the tutorial video of introduction to julia course on Julia academy in gci then I got an interest in this and I watched all the videos and completed the parallel computing course also (see screenshot image). So I want to comment on this course which is mentioned below.

• The course is well descriptive and instructor explained the course well.
• By watching all the videos of course I understand the logic of this course easily.
• introduction video is very interesting.

Some things which is noticable are :-

• Audio quality is not that much good.
• the course must be interactive for example the instructor may use some effects to interact the students to watch his course. He must use some presentation to explain the things instead of just writing all the same stuff on the same page to explain.
• video editing was poor.
• there must be quizzes or some exercise for those students who watch the course.
• instructor is hesitating to explain the things efficiently like real life examples were negligible in the course.
• there is no video of instructor in gpu topic which is required for interactive video.

But overall the course is good and able to make me understand what actually the parallel computing is.😊

**Comment by Redeem-Grimm-Satoshi** [comment]
This course made me understand parallel computing and how it's been done in Julia. Some few improvements could be done to make it more engaging and also improve user experience.

## Course Description
A solid course description could be given as I earlier proposed on the other courses. This will give a better understanding of the users.

## Course Objective
A course objective which will enable the user to know what he/she will be capable of doing after completing the course (this makes the user more excited).

## Course Requirement
This enables the user to know what is required of him/her inorder to complete the course with ease.

## Shorten Video Lenght
Honestly speaking, as soon as i enrolled in the course and saw the various video lengths especially (Serial Performance, Multithreading, Distributed Computing) i was somewhat discouraged, not because i find the course not interesting but because my data bundle at that time wasn't sufficient but did complete it when i reactivated my bundle. I think the max video length should be 30minutes which will be less boring and stop some users from sleeping.

## Review Questions
Short review questions should be given so users can remember what have been taught

## Leader's Board
A leader's board should be created to engourage competitiveness which will enable users to learn more.

**Comment by TheComputerM** [comment]
The course was amazing and easy to understand. Just a few points to be noted.

- Videos were to long and were not easily able to capture attention.
- No list of dependencies and the environment the teacher was using
- Video and audio quality was not good but it neither was bad.
- No exercises to test what we had learnt.
- The summary of the lesson at the end was incredible.
- Time stamps are needed.
- Provide difficulty level of course at beginning.

**Comment by Anikamittal23** [comment]
Although the course was good.But it needs some improvements.
1.Each video was very long and it needs to be shorten in small parts.
2.Sound quality was not very much good.
3.The PDF which contain codes were not in an organized way.
4.Some examples should be given to make the course more easy to understand.
HOPE YOU WORK ON MY IMPROVEMENTS
THANKS

**Comment by Anikamittal23** [comment]
I found this to be very helpful but not able to understand few points .
Some videos were too long because of which it become boring.
Some questions should be asked so that we can see how much and well we understood.

But overall the course was best and helpful

**Comment by saikishore222** [comment]
overall the course is good
improvements:-
1)course should be contain some quizzes,after every sort of videos
2)and also it should be contain some real life examples
3)audio and video clarity was not good,it needs to be better

**Comment by jatin2003** [comment]
The Course was overall good. Some improvements could be implemented:-

1. The audio volume should be more clear.

2. Some videos like "Multithreading", "Distributed Computing" & "Serial Performance" can be made short as long videos creates boresome.

3. The progress bar bug is still there.
![Julia](https://user-images.githubusercontent.com/56562571/72229949-3c5a9980-35d8-11ea-94d1-420de2fb5ce8.PNG)

**Comment by Bopoooo** [comment]
The instruction on the website is quite clear.
but there are still some improvements can be made.
1) try to use a better recording device, i can't hear the comment clearly.
2) I'm sorry that as a non native english speaker, I hope that you can add a subtitle for me to have a much better learning experience.
3) The length of some videos are a bit long, maybe you can divide them into more specific topic or make a short conclusion page.

**Comment by aasangamnerkar** [comment]
The course was decent and was an interesting topic, but there are a few potential improvements.
1. Turn up the mic volume while recording or normalize all of the audio files. The volume was VERY low on the mic and I had to turn up my computer almost to max just to understand what the instructor was saying.
2. Make guided notes/powerpoints that follow along with the video. Sometimes I find it easier to read along with a video when I am watching a video as it helps me learn better.
3. More examples that the student can do on their own would vastly improve learning.
4. Questions about the course that pop up as the video progresses would be beneficial.
5. One could "cheat" the course by spamming complete and continue. This needs to be fixed

**Comment by itqorst03** [comment]
### I took the Intro to Julia course and here's my review:

1) I got to know about the basics quite well.
2) It would be better if the course had subtitles.
3) The audio quality in the videos could have been better.
4) After every video, there should be a short quiz.
5) The course should be a bit more interactive.
6) I think the course is a little-bit fast paced for a person who does not know anything about 
     programming.

**Comment by aftex261** [comment]
Hey everyone,
Places of improvement in this course are 
1. The webcam in the introduction video was hiding some of the information in the graph.
So it should be adjusted as it's also the case with deep learning course.
2. The voice of the instructor in the video is too slow that we have to maximize the volume of the computer system.
3.In the performance overview lecture there could be another example other than sum as it's example has been illustrated in previous courses for benchmark testing.
4.There can be short quizzes added at last of every lecture.
5.The multithreading lecture and distributed computing lectures are good but they can be divided into short lectures making them easy to understand.
At last,I would like to say that I liked the course very much inspite of these improvements and I would like to give it a 👍 and a rating of 4/5.
Thanks everyone for reading.

**Comment by maxMurakami** [comment]
Overall I thought the course was engaging. Here are some things I feel like can be improved.
First, at 2:28(first video), the instructors face is in the way of the graph. Though this isn't much of an issue, it would be nice if it were fixed. I would much rather prefer the instructor in a separate screen off of the main screen with all of the information. Like two boxes next to each other. Second,  for the first minute of the introduction video there is a white noise in the background which is distracting. Third, the Multithreading video has poor audio quality, which I feel makes the video harder to watch. Onto of the quality, the voice is often breaking up which is quite annoying. Lastly, the Disrupting Computing video is quite long and I feel as though it could be broken in different sections/parts to make it easier for the viewer to understand.

**Comment by tokleejoon** [comment]
The course is good and interesting. However, the length of some videos are a bit long, maybe you can divide them into smaller size videos. There was also
 no quiz so we could not test our knowledge.

**Comment by rajat-png** [comment]
I've sucessfully completed the Complete the Parallel Computing course on JuliaAcademy.com. 
FEEDBACK :
The course is good and best but I've gave some feedback-
1- The tutorial video is too long, video should be minimum 10-15 minute.
2- The audio is not clear, video should be add subtitle.
3- The webcam video in the introduction video was hiding some graph. So I suggest should be adjusted the webcam video.
4- After completed the course not given the completed certificate, So I've suggest should be add completed certificate the course.
Thanks.

**Comment by tokleejoon** [comment]
The lessons made me learn a lot of new knowledge and gain new insights about parallel programming. The teacher was clear in explaining the parallel computing lesson such as multi-threading, SIMD,etc.
I feel that what can be improved on is the further elaboration of the lesson, such as the multi-threading lesson. I watched it a few times and did some research until I understood. I feel that if more could be taught, it would be more beneficial to me and other people viewing the lesson. 
Another point that I feel that could be improved on is the video on Distributed Computing. The voice of the teacher is a bit muffled and causing me to feel a little bored listening to that section. If the voice could be adjusted until it can be heard clearly, then I feel that I would be better. However, the contents were interesting to a point that I fully understand. I hope you take my feedback. Thank you!

**Comment by dhruv2604-create** [comment]
Hi everyone! I recently completed the " Parallel Computing" Course on Julia Academy. As a person who has almost no knowledge of Parallel Computing, it is a pretty good course. Although there are some suggestions that I would like to make:-
1. The audio should definitely be improved.
2. The duration of videos for example "Distributive Computing" (almost 66 mins) is too long for a single lecture. Hence, shorter videos should be made.
3. There should be comment sections where users can complement, suggest, as well as ask questions based on the lectures and the lecturers can answer. Also, certain live QnAs should be held with users to further develop knowledge of users.
4. New courses should be made aligned with new versions of Julia.
5. There should be a feature for users to practice alongside listening to lectures on the site itself.
6. Tests should be taken after a user completes a certain component of the course and he or she should only be able to advance after successfully completing the test.

**Comment by Airiinnn** [comment]
**Positives:**
1. Explanations were very clear and easily understood. Explaining what each macro and function did was really helpful as it allowed to understand what each code was doing. Comparing the time taken for each code to run and then explain the difference was also useful as it allows us to avoid these common mistakes in the future.
2. The pace of the videos were just right, going through the code and giving us ample time to understand it without pausing.

**Areas for improvement:**
1. Audio quality isn’t really good. It gets really choppy and unclear at some points that I could barely hear what he’a saying. There was also phone ringing at one point of the Parallel Algorithm video which was quite distracting. 
2. Lack of practices/quizzes. Although I learnt the concepts of parallel programming through this course, I’m not confident in my ability to write it out in code. Practices or code written on the spot would be helpful in apply these concepts.
3. More examples of each concept would be nice, maybe adding some more at the end of the notebook for us to self-read.
4. Videos may be outdated. I remembered a part of the video mentioning about certain features in newer versions of Julia that weren’t released yet at that time but it is right now.
5. Progress bar a bit buggy, completed the course 100% but it displayed 78% at the course's home page.

Overall, it’s a great course for introducing parallel computing concepts but more practice is required in order to fully grasp these concepts and be able to utilize them effectively.

**Comment by aaaaaaaaaaaaaaaaace** [comment]
The video tutorials should be as beginner-friendly as possible, and not always assume that the audience have computing knowledge wanting to know a new language. For example the video assumes that the audience knows what strings or string interpolation/concatenation means and only demonstrates how to do them in julia.

Also, the video should have the teacher typing out the code as she is explaining the julia concepts and not have them pre-typed already and press shift enter, so that it would be easier to pace the lessons.

Other than that, I really enjoyed these lessons. The person was straightforward without beating around the bush unnecessarily, and I can learn much from this introductory course. I would share about this course with my other fellow computing peers :)

**Comment by Akshat-mehrotra** [comment]
Aside from the evident Audio and Video issues with the course recording, and aside from the unneeded length of the videos, this, in my opinion, is a very comprehensive and inclusive course. The explanations about the whys and the hows of functions and output of those functions, unlike some other courses, is very deep. There are minute presentation errors in the introduction video where the graph is blocked and in some videos, the background noise of telephones is quite audible.

**Comment by jennifererwangg** [comment]
Action items:
-	Before jumping straight into the video, maybe add a few slide decks explaining the concept of the video more clearly (i.e. In the data structures video, define definitions of dictionaries, tuples, and arrays) instead of using examples to teach. In addition, I think there should be more videos involving data structures, with each video covering a single data structure instead of putting them all together into one video.
-	Another reason to incorporate slide decks into your presentation is that it can help beginners to visualize concepts. I found visualization (i.e. arrays, functions) very helpful when I was learning how to program.
-	Make coding problems so that learners can apply what they have learned right away. Multiple choice questions were good for review of concepts; however, if users want to learn the Julia Language, it’s best to practice the language itself.
-	Needs more introductory videos. The difficulty of the videos is jumping from beginner to those of an intermediate too abruptly, and the lecturer sometimes use technical vocabularies in introductory videos. This might be hard for beginners to follow.
-	When filming the videos, it’s better to also film the mouse pointer. Otherwise, it is a little difficult to see which button the person hit, and thus makes learning harder.
-	Include links to where learners can gain help in the videos

Pros of the course:
-	Clear agenda listed at the beginning of each video
-	Clear audio & soothing voice
-	Good video lengths

**Comment by AnimatorOfSouls** [comment]
Good:
Fairly easy to understand for a noob like me.

Bad:
Webcam sometimes covered information on the screen.
Some videos are too long, would be nice to split them up into shorter chunks.
Some of the videos were a bit laggy and I ended up getting distracted by the mouse jumping around the screen.

Requests:
Captions on the videos which can be toggled (like the ones on YouTube).
A text summary of the contents covered in the video underneath the video with timestamps.
List of new words that may be used in each computing with a basic definition (I had to Google a few).
